### ISSUE TITLE
where is the README?

### ISSUE THREAD

**Issue by encryptblockr** [devtud/pygramtic#1]
no documentation whatsoever

**Comment by devtud** [comment]
Indeed, a Readme would be useful.

Shortly, this repo should be able to provide all the data structures of telegram bot docs as Pydantic models. You should be able to use them to quickly create a fastapi based  telegram bot. 

Contributions are welcomed as I didn't find time to sync the models with telegram api for some time.

**Comment by encryptblockr** [comment]
then dont spam pypi.org with stuffs like this
that is a **HUGE** dis-service to open-source
